[OpenCL] Registers AvgPoolGrad using SYCL kernel
lukeiwanski/tensorflow pull request #100
Opened 2017-06-26 15:15 UTC by jeffmak

2017-06-27 17:28 UTC, lukeiwanski requested changes
There is quite big overlap between this PR and https://github.com/lukeiwanski/tensorflow/pull/99 .. it might be better to create one PR for both.

2017-06-27 17:28 UTC, lukeiwanski commented on tensorflow/core/kernels/avgpooling_op.cc
> +                            .Label("cudnn"),
is that label needed here?

2017-06-27 17:28 UTC, lukeiwanski commented on tensorflow/core/kernels/pooling_ops_common.h
> +#ifdef TENSORFLOW_USE_SYCL
This change set might cause conflict as it appears in two pull requests. ( https://github.com/lukeiwanski/tensorflow/pull/99 )

2017-06-28 13:06 UTC, jeffmak commented
Closing PR, refer to #105.

2017-06-28 13:06 UTC, closed without merging