[OpenCL] Registers MaxPoolGrad and MaxPoolGradGrad
lukeiwanski/tensorflow pull request #103
Opened 2017-06-27 13:25 UTC by jeffmak

@jwlawson I had to inline the atomic add functions because including sycl_util.h for more than one file gave me linking issues. Let me know if there are better ways to do this :)

2017-06-27 17:40 UTC, lukeiwanski requested changes
Overall looks good!

2017-06-27 17:40 UTC, lukeiwanski commented on tensorflow/core/kernels/maxpooling_op.cc
> +              n * p_.in_rows_ * p_.in_cols_ * p_.depth_ +
can you run clang format on your code?

2017-06-27 17:40 UTC, lukeiwanski commented on tensorflow/core/kernels/pooling_ops_common.h
> +#ifdef TENSORFLOW_USE_SYCL
That will cause conflicts.. can you make PR for SYCL2DPoolParams on it's own? So we can merge that in ahead of the other changes?

2017-06-27 17:40 UTC, lukeiwanski commented on tensorflow/core/util/sycl_util.h
> +inline void SyclAtomicAdd(__attribute__((address_space(1))) T* address,
That should be a PR on it's own. The smaller PR the better :)

2017-06-28 13:09 UTC, jeffmak commented
Closing PR, refer to #106.

2017-06-28 13:09 UTC, closed without merging