Add SYCL device selection
lukeiwanski/tensorflow pull request #174
Opened 2017-11-01 11:32 UTC by Rbiessy

See http://jira:8080/browse/TF-158
This will simply change the order the SYCL devices are added. By default TF will still use the first device added.

With these changes the devices are added in the following order:
1. if the environment variable TENSORFLOW_SYCL_USE_PLATFORM_NAME_VENDOR_ID is set to <platform_name>:<vendor_id>, this specific device will be added. It is useful if there are multiple similar platforms or similar devices
2. if the environment variable TENSORFLOW_SYCL_USE_DEVICE_TYPE is set to gpu, cpu or acc, the first device of the specified type will be added. It should only be used if there is one device of the given type
3. add all gpus (in non-deterministic order)
4. add all accelerators (in non-deterministic order)
5. add all cpus (in non-deterministic order)

2017-11-02 19:26 UTC, lukeiwanski requested changes

2017-11-02 19:26 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_device.cc
> +  auto platform_vendor_cstr = std::getenv("TENSORFLOW_SYCL_USE_PLATFORM_NAME_VENDOR_ID");
Is there a way to avoid enviroment variables?

It seems that equivalent for GPU is done in config.proto via CUDA_VISIBLE_DEVICES (https://github.com/lukeiwanski/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L47)

2017-11-02 19:26 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_device.cc
> +  auto device_type = std::getenv("TENSORFLOW_SYCL_USE_DEVICE_TYPE");
There is slightly bigger question that we need to ask here and perhaps @benoitsteiner could help out here.. 
How should we handle situation when users system has multiple OpenCL platforms? 
What is desired granularity - should user be able to place Ops on different devices? Or should we pass desired device to the session? Or shall we stick to rigid priority list? OpenCL: Accelerators, GPU, CPU, Host?

2017-11-03 10:19 UTC, Rbiessy commented on tensorflow/core/common_runtime/sycl/sycl_device.cc
> +  auto platform_vendor_cstr = std::getenv("TENSORFLOW_SYCL_USE_PLATFORM_NAME_VENDOR_ID");
No I am pretty sure we can't. With TF, all we can do to select a device is based on a device id which is just an index in a device list. OpenCL devices don't have such an id. What we have is a list of platforms and for each platform a list of devices and the order we get these platforms and devices is not guaranteed to be always the same.

2018-06-01 16:30 UTC, Rbiessy commented
This can be closed, Eigen has a good enough workaround to avoid that now.
I'll keep the changes in my branch just in case but I'm closing the PR.

2018-06-01 16:30 UTC, closed without merging