[OpenCL] Fixes core_rnn_cell_test
lukeiwanski/tensorflow pull request #8
Opened 2017-05-04 09:02 UTC by Zakor94

I made SYCL use the same implementation as the CPU for AddBias, not sure if this is a good idea though?
I haven't changed anything for core_rnn_test yet but 2 functions seem to pass.

2017-05-04 11:26 UTC, Zakor94 commented
Three points I am unsure about the fix for core_rnn_test:
  - REGISTER_KERNEL_BUILDER of "TensorArrayGrad", "TensorArraySize" and "TensorArrayClose" for DEVICE_GPU not guarded by #if GOOGLE_CUDA. It works because it is not templated by the device. Should we add both guards?
  - GOOGLE_CUDA register kernels for GPU_NUMBER_TYPES, complex64, complex128 and sometimes bfloat16. Is GPU_NUMBER_TYPES_NO_HALF enough for SYCL? Should we register op on the cpu for these other types?
  - TensorArrayUnpackOrScatterOp has no special case for int32 on CPU (but TensorArrayPackOrGatherOp has one). This asymetry looks weird.

2017-05-05 14:26 UTC, lukeiwanski requested changes

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/contrib/rnn/python/kernel_tests/core_rnn_test.py
> -    if not test.is_gpu_available() or test_util.is_sycl_enabled():
Can that be done as a separate commit? This already has been reverted in the opencl_improvements branch and will cause merge conflict

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/contrib/rnn/python/kernel_tests/core_rnn_test.py
> -    if not test.is_gpu_available() or test_util.is_sycl_enabled():
Can that be done as a separate commit? This already has been reverted in the opencl_improvements branch and will cause merge conflict

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.cc
> +
Spare new line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.cc
> +
spare new line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.cc
> +
spare new line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.h
> +#if GOOGLE_CUDA
is that wrapper needed for CUDA ? they do not use it for the GPUDevice typedef in general

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.h
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.h
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.h
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.h
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +#define CALL_REGISTER_123V(call, name, ...) \
can we rename it to CALL_REGISTER_V123 ? or something more descriptive?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
if the #if GOOGLE_CUDA needed here?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
is #if GOOGLE_CUDA that needed?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
is #if GOOGLE_CUDA needed here?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:26 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
spare line?

2017-05-05 14:29 UTC, lukeiwanski commented
> REGISTER_KERNEL_BUILDER of "TensorArrayGrad", "TensorArraySize" and "TensorArrayClose" for DEVICE_GPU not guarded by #if GOOGLE_CUDA. It works because it is not templated by the device. Should we add both guards?

We should not touch CUDA code if it can be avoided.

> GOOGLE_CUDA register kernels for GPU_NUMBER_TYPES, complex64, complex128 and sometimes bfloat16. Is GPU_NUMBER_TYPES_NO_HALF enough for SYCL? Should we register op on the cpu for these other types?

We do not support complex numbers yet. For now lets make it work with scalar types ( float, double )

> TensorArrayUnpackOrScatterOp has no special case for int32 on CPU (but TensorArrayPackOrGatherOp has one). This asymetry looks weird.

Agree, that looks odd. For now follow what CUDA is doing.

2017-05-05 14:42 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.cc
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:43 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.h
> +#if GOOGLE_CUDA
That's weird because I have seen a lot of typedef for GPUDevice using #if GOOGLE_CUDA so I was wondering if it was a missing one

2017-05-05 14:44 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.cc
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:45 UTC, lukeiwanski commented on tensorflow/core/kernels/tensor_array.cc
> +
For SYCL we didn't. Can we dedicate another PR to fixing the formating later on?

2017-05-05 14:45 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.cc
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:45 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.h
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:45 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.h
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:45 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.h
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:45 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array.h
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:46 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array_ops.cc
> +#define CALL_REGISTER_123V(call, name, ...) \
Yes CALL_REGISTER_V123 makes more sense

2017-05-05 14:46 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 14:46 UTC, Zakor94 commented on tensorflow/core/kernels/tensor_array_ops.cc
> +
The new line is intended to match #if GOOGLE_CUDA coding style

2017-05-05 15:27 UTC, Zakor94 commented
Should be good now.

2017-05-09 13:47 UTC, lukeiwanski approved these changes

2017-05-09 13:49 UTC, merged