[OpenCL] Fixes image_ops_test
lukeiwanski/tensorflow pull request #9
Opened 2017-05-05 11:34 UTC by Zakor94

2017-05-05 14:30 UTC, lukeiwanski requested changes

2017-05-05 14:30 UTC, lukeiwanski commented on tensorflow/python/ops/image_ops_test.py
> -    if test_util.is_sycl_enabled():
Can that be done in separate commit?

2017-05-05 14:30 UTC, lukeiwanski commented on tensorflow/python/ops/image_ops_test.py
> -    if test_util.is_sycl_enabled():
Can that be done in separate commit?

2017-05-05 14:59 UTC, Zakor94 commented
Should be good now.

2017-05-09 16:16 UTC, lukeiwanski approved these changes

2017-05-09 16:16 UTC, merged