[OpenCL] Registers AvgPool using SYCL kernel
lukeiwanski/tensorflow pull request #99
Opened 2017-06-26 15:08 UTC by jeffmak

Question: Since SYCL2DPoolParams is used in most 2D pooling operations, is it appropriate to move the associated code to tensorflow/core/util/sycl_util.h?

2017-06-27 17:22 UTC, lukeiwanski requested changes
That looks good! Couple minor comments.

2017-06-27 17:22 UTC, lukeiwanski commented on tensorflow/core/kernels/avgpooling_op.cc
> +#endif
minor: #endif -> #endif  // TENSORFLOW_USE_SYCL

2017-06-27 17:22 UTC, lukeiwanski commented on tensorflow/core/kernels/avgpooling_op.cc
> +    auto input_access =
Indentation for this block is missing

2017-06-28 13:05 UTC, jeffmak commented
Closing PR, refer to #105.

2017-06-28 13:05 UTC, closed without merging